#!/bin/zsh

# Check if running with sudo
if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root" 
    exit 1
fi

# Check if argument is provided
if [ $# -ne 2 ]; then
    echo "Usage: $0 install <package_name>"
    exit 1
fi

# Extract package name from argument
if [ "$1" != "install" ]; then
    echo "Usage: $0 install <package_name>"
    exit 1
fi

package_name=$2

# Function to download and install to system bin directory
download_and_install() {
    url=$1
    filename=$(basename "$url")
    echo "[-] install dependencies: $filename"
    curl -LO "$url" || { echo "[!] Failed to download dependencies: $url"; exit 1; }
    tar -xzf "$filename" || { echo "Failed to extract $filename"; exit 1; }
    # Assuming the extracted folder contains binaries to add to system bin directory
    sudo cp -r "./$package_name/$package_name" "/usr/local/bin/$package_name"
    echo "[+] installed dependencies: $filename"
}

download_and_installi() {
    echo "[-] install"
    url=$1
    filename=$(basename "$url")
    curl -LO "$url" || { echo "Failed to download $url"; exit 1; }
    tar -xzf "$filename" || { echo "Failed to extract $filename"; exit 1; }
    # Assuming the extracted folder contains binaries to add to system bin directory
    sudo cp -r "./$package_name/$package_name" "/usr/local/bin/$package_name"
    echo "[+] installed: $package_name"
}

echo "Download and Install Start =>"

# Step 2: Connect to server and retrieve pkg.json
json_url="https://dl.kamu.jp/$package_name/pkg.json"
pkg_json=$(curl -sS "$json_url") || { echo "Failed to retrieve pkg.json from $json_url"; exit 1; }

# Step 3: Download and add dependencies to system bin directory
dependencies=$(echo "$pkg_json" | jq -r '.dependencies | to_entries[] | .value')
for url in $dependencies; do
    echo "Download and Install dependencies: $url"
    download_and_install "$url"
done

# Step 4: Download and add main package to system bin directory
main_url=$(echo "$pkg_json" | jq -r '.url')
echo "Download and Install: $main_url"
download_and_installi "$main_url"

echo "[+] Installation of $package_name and that dependencies completed successfully"
